---
title: "Piping stuff"
output: html_notebook # output could be whatever
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
# load data
artists <- read_csv('artists.csv')
```

```{r}
# select columns
chosen_cols <- artists %>%
  select(-country,-year_founded,-albums)
head(chosen_cols)
```

```{r}
# filter rows
popular_not_hip_hop <- chosen_cols %>%
  filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop')
head(popular_not_hip_hop)
```

```{r}
# arrange rows
youtube_desc <- popular_not_hip_hop %>%
  arrange(desc(youtube_subscribers))
head(youtube_desc)
```

```{r}
# however, we can condense the above three to a single thing, by condensing using pipe
# select columns, filter and arrange rows
artists <- artists %>%
              select(-country, -year_founded, -albums) %>% filter(spotify_monthly_listeners > 20000000, genre != 'Hip Hop') %>% arrange(desc(youtube_subscribers))
head(artists)
# this gives the same result as the head(youtube_desc)
```