---
title: "Manipulating columns"
output: html_notebook # output could be whatever
---

```{r message=FALSE, warning=FALSE}
# load libraries
library(readr)
library(dplyr)
# load data
dogs <- read_csv('dogs.csv')
```

```{r}
# add average height column
dogs <- dogs %>%
  mutate(avg_height = (height_low_inches + height_high_inches) / 2)
# adding more:
dogs <- dogs %>%
  mutate(avg_height = (height_low_inches + height_high_inches) / 2, newer_things = TRUE)

# transmute: just showing the columns that are added
dogs <- dogs %>%
          transmute(breed = breed, avg_height = (height_low_inches + height_high_inches)/2,
                avg_weight = (weight_low_lbs + weight_high_lbs)/2,
                rank_change_13_to_16 = rank_2016 - rank_2013)
# saving colnames of a data frame
col_names <- colnames(dogs)

# rename columns using "rename(new_col_name = old_col_name)" function
dogs <- dogs %>%
          rename(avg_height_inches = avg_height, avg_weight_lbs = avg_weight, popularity_change_13_to_16 = rank_change_13_to_16)
```